theme: jekyll-theme-cayman
title: ["eBay TSV Utilities"]
description: ["Command line utilities for tabular data files written in the D programming language."]
encoding: utf-8
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  
